# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: IV new world site
email: Iscovalardpro@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hello world, I'm Isco Valard talking to you in somewhere in this planet, 
  asking if you're ready to hear some good vibes and nice music.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://iscovalard.github.io" # the base hostname & protocol for your site
twitter_username: IscoValard
github_username:  IscoValard

# Build settings
markdown: kramdown
